NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing/swaggerui.xml"
    prefix:   /doc
igsem_auth:
    resource: "@IgsemAuthBundle/Resources/config/routing.yml"
app:
    resource: '@AppBundle/Controller/'
    type: annotation
