igsem_auth:
    resource: "@IgsemAuthBundle/Resources/config/routing.yml"
    prefix:   /
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc
app:
    resource: '@AppBundle/Controller/'
    type: annotation
