language: php
sudo: false
dist: trusty
php:
    - '7.1'
services:
    - memcached
    - mongodb
    - redis-server
before_script:
    # to fasten up installation with parallel downloading
    - composer global require hirak/prestissimo
    # install composer dependencies
    - composer install
before_install:
    - |
      # php.ini configuration
      INI=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
      phpenv config-rm xdebug.ini || echo "xdebug not available"
      echo date.timezone = Europe/Paris >> $INI
      echo memory_limit = -1 >> $INI
      echo session.gc_probability = 0 >> $INI
      echo opcache.enable_cli = 1 >> $INI
      echo apc.enable_cli = 1 >> $INI
      echo extension = ldap.so >> $INI
      echo extension = redis.so >> $INI
      echo extension = memcached.so >> $INI
      echo extension = mongodb.so >> $INI
# do not send success notifications, they have no value
notifications:
    email:
        on_success: never