language: php
sudo: false
dist: trusty
php:
    - '7.1'
matrix:
  fast_finish: true
  include:
    - php: 7.1
services:
    - memcached
    - redis-server
before_install:
    - composer self-update
    - |
      # php.ini configuration
      INI=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
      echo date.timezone = Europe/Paris >> $INI
      echo memory_limit = -1 >> $INI
      echo session.gc_probability = 0 >> $INI
      echo opcache.enable_cli = 1 >> $INI
      echo apc.enable_cli = 1 >> $INI
      echo extension = redis.so >> $INI
      echo extension = memcached.so >> $INI
# do not send success notifications, they have no value
install:
    - composer global require hirak/prestissimo
    - composer install
script:
    - phpunit --coverage-clover phpunit/clover.xml
    - php phpunit/cover.php phpunit/clover.xml 99
    - ./vendor/bin/php-cs-fixer fix src --rules=@Symfony --diff --dry-run -v
    - ./bin/console security:check --end-point=http://security.sensiolabs.org/check_lock
notifications:
    email:
        on_success: never