language: php
sudo: false
dist: trusty
php:
    - '7.1'
node_js:
  - "stable"
matrix:
  fast_finish: true
  include:
    - php: 7.1
services:
    - memcached
    - redis-server
addons:
    - mariadb
# Cache composer packages so "composer install" is faster
cache:
  directories:
    - $HOME/.composer/cache/files
before_install:
    - git submodule update --init
    - composer self-update
    - npm install yarn -g
    - |
      # php.ini configuration
      INI=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
      echo date.timezone = Europe/Paris >> $INI
      echo memory_limit = -1 >> $INI
      echo session.gc_probability = 0 >> $INI
      echo opcache.enable_cli = 1 >> $INI
      echo apc.enable_cli = 1 >> $INI
      echo extension = redis.so >> $INI
      echo extension = memcached.so >> $INI
# do not send success notifications, they have no value
install:
    - composer global require hirak/prestissimo
    - cd symfony-app && composer install
script:
    - phpunit --coverage-clover phpunit/clover.xml
    - php phpunit/cover.php phpunit/clover.xml 99
    - ./vendor/bin/php-cs-fixer fix src --rules=@Symfony --diff --dry-run -v
    # this checks that the YAML config files contain no syntax errors
    - ./bin/console lint:yaml app/config
    - ./bin/console lint:twig app/Resources
    - ./bin/console security:check --end-point=http://security.sensiolabs.org/check_lock
    - cd ../react-app && yarn install && yarn test -- -u && yarn flow && yarn coverage && yarn lint && yarn build
notifications:
    email:
        on_success: never