version: '3'

services:
  php:
    build: ./docker/php/
    environment:
      TIMEZONE: Europe/Bratislava
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./symfony-app:/var/www/app:cached
    working_dir: /var/www/app
  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
  db:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_USER=symfuser
      - MYSQL_PASSWORD=koronci22
      - MYSQL_DATABASE=symfony
    volumes:
      - ./db-data:/var/lib/mysql:rw
  webserver:
    image: nginx:latest
    depends_on:
      - php
      - redis
      - db
    volumes:
      - ./symfony-app:/var/www/app
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8080:80
volumes:
  php:
  redis: